export enum EndPoints {
  SIGN_IN = 'auth/signin',
  SOCIAL_SIGN_IN = 'auth/socialSignIn',
  SIGN_UP = 'auth/signUp',
  REFRESH_ACCESS_TOKEN = 'auth/refreshAccessToken',
  DASHBOARD = 'dashboard',
  TEXT_SEARCH = 'textSearch',
  TEXT_SEARCH_AUTO_COMPLETE = 'textSearchAutoComplete',
  BLOG = 'blog',
  BLOG_PUBLISHED = 'blog/published',
  BLOG_SAVED = 'blog/saved',
  BLOG_LIKE = 'blog/like',
  BOOKMARK = 'blog/bookmark',
  BLOGS_BOOKMARKED = 'blog/bookmarked',
  CATEGORY = 'category',
  PAYMENT = 'payment',
  SUBSCRIPTION_PLANS = 'subscriptionPlans',
  CREATE_ORDER = 'createOrder',
  CHANGE_PASSWORD = 'auth/changePassword',
  SUBSCRIPTION_DETAILS = 'activeSubscriptionPlan',
  SEND_PASSWORD_VERIFICATION_EMAIL = 'auth/sendPasswordResetEmail',
  VERIFY_EMAIL = 'auth/verifyemail',
  RESET_PASSWORD = 'auth/resetPassword',
  LOG_OUT = 'auth/logOut',
}
